config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get '/home/about', to: 'homes#about',as: 'about'
  devise_for :users, :controllers => {
  	:registrations => 'users/registrations',
  	:sessions => 'users/sessions'
  }

  resources :books
  resources :users
  resources :post_images, only:[:new, :create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :image

  # deviseでemailを不必要にする
  def email_required?
  	false
  end

  def email_changed?
  	false
  end

  has_many :books, dependent: :destroy
  has_many :post_images, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :destroy, :show, :update, :create, :new]
  before_action :correct_user, only: [:edit, :update]

  def edit
  	@user = User.find(params[:id])
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def new
    @book = Book.new
  end

  def update
  	@user = User.find(params[:id])
  	 if @user.update(user_params)
        flash[:notice] = "User was successfully updated."
        redirect_to user_path(@user.id)
      else
        @alert = "error"
        render :edit
      end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end

  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<p id="notice"><%= @alert %></p>
<h2>User info</h2>
<%= form_for(@user) do |f| %>
	<div class="field">
		<label for="name">Name</label>
		<%= f.text_field :name, autofocus: true, class:"name", id:"name" %>
	</div>

	<div class="field">
		<label">Image</label>
		<%= f.attachment_field :image, class: "user_image", fallback: "no_image.jpg"%>
	</div>

	<div class="field">
		<label for="introduction">Introduction</label>
		<%= f.text_area :introduction, autofocus: true, class:"introduction", id:"introduction" %>
	</div>

	<%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<!-- 「_userinfo.html.erb」の呼び出し -->
<div class="col-xs-3">
<%= render 'layouts/userinfo', books: @books , user: current_user %>
<%= render 'layouts/newbook', book: @book , books: @books %>
</div>
<div class="col-xs-9">
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		  <% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag user, :image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
				<td><%= user.name %></td>
				<td><%= link_to 'show', user_path(user.id), class: "user_#{user.id}" %></td>
			</tr>
		  <% end %>
		</tbody>
	</table>
</div>

app/views/users/show.html.erb
<!-- 「_userinfo.html.erb」の呼び出し -->
<div class="col-xs-3">
<%= render 'layouts/userinfo', user: @user %>
<%= render 'layouts/newbook', book: @book ,books: @books %>
</div>
<div class="col-xs-9">
	<h2>Books（マイページ）</h2>
	<table class="table table-hover table-inverse">
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
		</tr>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to user_path(current_user.id) ,class: "user_#{@user.id}" do  %>
				<%= attachment_image_tag book.user, :image, :fill, 50, 50, format: 'jpeg' %>
				<% end %>
			</td>
			<!-- user_path(current_user.id) -->
			<td><%= link_to book.title, book_path(book.id),class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
		</tr>
		<% end %>
	</table>
</div>