config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get '/home/about', to: 'homes#about',as: 'about'
  devise_for :users, :controllers => {
  	:registrations => 'users/registrations',
  	:sessions => 'users/sessions'
  }

  resources :books
  resources :users
  resources :post_images, only:[:new, :create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_newbook.html.erb
<h2>New book</h2>
<%= form_for(book) do |f| %>

<div class="field row">
	<label for="book_title">Title</label><br>
	<%= f.text_field :title, class: "col-xs-12 book_title" %>
</div>
<div class="field row">
	<label for="book_body">Opinion</label><br>
	<%= f.text_area :body, class: "col-xs-12 book_body" %>
</div>
<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
<% end %>

app/views/layouts/_userinfo.html.erb
<% if flash[:notice] %>
	<p style="color: green"><%= flash[:notice] %></p>
<% end %>
<p id="notice"><%= @alert %></p>
<!-- エラーメッセージの表示 -->
<% if user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h2>User info</h2>
<%= attachment_image_tag user, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
<table class='table'>
	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
</table>
<% if current_user.id == user.id %>
  <div class="row">
	<%= link_to "", edit_user_path(current_user.id) ,class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersAdvanced</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to "Users", users_path, class: "glyphicon glyphicon-user users" %></li>
            <li><%= link_to "Books", books_path, class: "glyphicon glyphicon-book books" %></li>
            <li><%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
          <% else %>
            <li><%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to "About", about_path, class: "glyphicon glyphicon-link about" %></li>
            <li><%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
            <li><%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          </ul>
          <% end %>
        </nav>
      </div>
    </header>
    <!-- 新規登録・ログイン時にメッセージを表示 -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </body>
</html>